#!/bin/sh

##########
#
#   michaelfm1211's Advent of Code input and example getter
#
# This script will get the Advent of Code input and example and store them into
# the files "in" and "ex" (respectively) in the current directory. By default,
# this script will attempt to get the current Advent of Code challenge, but the
# script can also get the input for any day on any year.
#
# To use, you must provide your Advent of Code session cookie, which can be
# seen in browser's cookie manager or the Network tab of the devtools. This
# script will read your session cookie from ~/.config/advent_of_code_session
# The cookie's value must be the only line in the file.
#
# NOTE: Obviously, this script can only get the current Advent of Code challenge
# if there is a currently ongoing challenge. So, if you don't specify a day and
# year outside of December 1st through December 25th, you'll get an error.
#
##########

if [ "$#" -gt 2 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "usage: $0 [day] [year]"
	exit 1
fi

DAY=`TZ=EST date +"%_d" | sed 's/ //'`
if [ "$#" -ge 1 ]; then
	DAY="$1"
fi

YEAR=`date +"%Y"`
if [ "$#" -eq 2 ]; then
	YEAR="$2"
fi

# ex
curl -s "https://adventofcode.com/$YEAR/day/$DAY" | awk '{print}' ORS='__NEWLINE__' | perl -ne 'm/or example.+?<code>(.*?)<\/code>/ && print "$1"' | sed 's/__NEWLINE__/\n/g' > ex

# in
SESSION=`cat ~/.config/advent_of_code_session`
curl -s -o "in" --cookie "session=$SESSION" "https://adventofcode.com/$YEAR/day/$DAY/input"
